/**
 * bgdata.js — 背卡骨架資料
 *
 * 由 tools/build-bg.mjs 產生，不要手改，下次重跑會整份蓋掉。
 * 要改名稱或補寶可夢清單，改 js/bgevents.js，那一份會逐欄覆蓋這裡。
 *
 * 欄位：
 *   id       使用者紀錄的鍵，發布後不可更改
 *   asset    上游檔名，圖片網址由 js/backgrounds.js 的 bgUrl() 組出來
 *   series   收納夾，名稱在 js/bgseries.js
 *   scope    global 全球 / regional 地區限定
 *   en       英文名稱，來自 Serebii，對不到時用檔名推
 *   date     活動期間，來自 Serebii
 *   code     game master 的正式代號，用來對上游，畫面上不顯示
 *   vfx      上游那張圖只是底層，玩家看到的卡面還疊了一層特效。
 *            true 的話畫面上會看到跟遊戲裡不一樣的圖，只能將就
 *   pokemon  可能帶有這張背卡的條目，骨架一律留空
 */

export const BG_CARDS = [
  { id: "2025-kr-pyeongchang-winter-festival", asset: "lc_2025_kr_pyeongchangWinterFestival", series: "lcmisc", scope: "regional", en: "Pyeongchang Winter Festival", date: "January 19th - January 25th", code: "LC_2025_KR_PYEONGCHANG_WINTER_FESTIVAL", vfx: false, pokemon: [] },
  { id: "2026-br-001", asset: "lc_2026_BR_001", series: "lcmisc", scope: "regional", en: "2026 Br 001", date: "", code: "LC_2026_BR_001", vfx: false, pokemon: [] },
  { id: "2026-npb-belluna", asset: "lc_2026_NPB_belluna", series: "npb", scope: "regional", en: "Belluna", date: "Spring 2026", code: "LC_2026_NPB_010", vfx: false, pokemon: [] },
  { id: "2026-npb-chunichi-dragons", asset: "lc_2026_NPB_chunichiDragons", series: "npb", scope: "regional", en: "Chunichi Dragons", date: "Spring 2026", code: "LC_2026_NPB_012", vfx: false, pokemon: [] },
  { id: "2026-npb-hiroshima-carp", asset: "lc_2026_NPB_hiroshimaCarp", series: "npb", scope: "regional", en: "Hiroshima Carp", date: "Spring 2026", code: "LC_2026_NPB_006", vfx: false, pokemon: [] },
  { id: "2026-npb-hokkaido-fighters", asset: "lc_2026_NPB_hokkaidoFighters", series: "npb", scope: "regional", en: "Hokkaido Fighters", date: "Spring 2026", code: "LC_2026_NPB_013", vfx: false, pokemon: [] },
  { id: "2026-npb-koshien-hanshin-tigers", asset: "lc_2026_NPB_koshienHanshinTigers", series: "npb", scope: "regional", en: "Koshien Hanshin Tigers", date: "Spring 2026", code: "LC_2026_NPB_004", vfx: false, pokemon: [] },
  { id: "2026-npb-kyocera", asset: "lc_2026_NPB_kyocera", series: "npb", scope: "regional", en: "Kyocera", date: "Spring 2026", code: "LC_2026_NPB_009", vfx: false, pokemon: [] },
  { id: "2026-npb-rakuten-eagles", asset: "lc_2026_NPB_rakutenEagles", series: "npb", scope: "regional", en: "Rakuten Eagles", date: "Spring 2026", code: "LC_2026_NPB_005", vfx: false, pokemon: [] },
  { id: "2026-npb-softbank-hawks", asset: "lc_2026_NPB_softbankHawks", series: "npb", scope: "regional", en: "Softbank Hawks", date: "Spring 2026", code: "LC_2026_NPB_008", vfx: false, pokemon: [] },
  { id: "2026-npb-tokyo-swallows", asset: "lc_2026_NPB_tokyoSwallows", series: "npb", scope: "regional", en: "Tokyo Swallows", date: "Summer 2026", code: "LC_2026_NPB_003", vfx: false, pokemon: [] },
  { id: "2026-npb-toyama-allstars", asset: "lc_2026_NPB_toyamaAllstars", series: "npb", scope: "regional", en: "Toyama All Stars", date: "Summer 2026", code: "LC_2026_NPB_007", vfx: false, pokemon: [] },
  { id: "2026-npb-yokohama-stadium", asset: "lc_2026_NPB_yokohamaStadium", series: "npb", scope: "regional", en: "2026 Npb Yokohama Stadium", date: "", code: "LC_2026_NPB_001", vfx: false, pokemon: [] },
  { id: "2026-npb-yomiuri-giants", asset: "lc_2026_NPB_yomiuriGiants", series: "npb", scope: "regional", en: "Yomiuri Giants", date: "Spring 2026", code: "LC_2026_NPB_002", vfx: false, pokemon: [] },
  { id: "2026-npb-zozo-marine", asset: "lc_2026_NPB_zozoMarine", series: "npb", scope: "regional", en: "Zozo Marine", date: "Spring 2026", code: "LC_2026_NPB_011", vfx: false, pokemon: [] },
  { id: "2026-jp-red", asset: "lc_2026_jp_red", series: "lcmisc", scope: "regional", en: "2026 Jp Red", date: "", code: "LC_2026_JP_RED", vfx: false, pokemon: [] },
  { id: "2026-ppk-001", asset: "lc_2026_ppk_001", series: "lcmisc", scope: "regional", en: "2026 Ppk 001", date: "", code: "LC_2026_PPK_001", vfx: false, pokemon: [] },
  { id: "air-adv2024-bali", asset: "lc_AirAdv2024_bali", series: "airadv", scope: "regional", en: "Air Adventures Bali", date: "March 2nd - 3rd 2024", code: "LC_2024_BALI_AIRADVENTURES_001", vfx: false, pokemon: [] },
  { id: "air-adv2024-jakarta", asset: "lc_AirAdv2024_jakarta", series: "airadv", scope: "regional", en: "Air Adventures Jakarta", date: "September 21st - 22nd 2024", code: "LC_2024_JAKARTA_AIRADVENTURES_001", vfx: false, pokemon: [] },
  { id: "air-adv2024-surabaya", asset: "lc_AirAdv2024_surabaya", series: "airadv", scope: "regional", en: "Air Adventures Surabaya", date: "May 11th - 12th 2024", code: "LC_2024_SURABAYA_AIRADVENTURES_001", vfx: false, pokemon: [] },
  { id: "air-adv2024-yogyakarta", asset: "lc_AirAdv2024_yogyakarta", series: "airadv", scope: "regional", en: "Air Adventures Yogyakarta", date: "August 24th - 25th 2024", code: "LC_2024_YOGYAKARTA_AIRADVENTURES_001", vfx: false, pokemon: [] },
  { id: "cr-2026-001", asset: "lc_CR_2026_001", series: "lcmisc", scope: "regional", en: "Cr 2026 001", date: "", code: "LC_CR_2026_001", vfx: false, pokemon: [] },
  { id: "cherry-blossom-fest2025-yeouido", asset: "lc_CherryBlossomFest2025_yeouido", series: "lcmisc", scope: "regional", en: "Cherry Blossom Fest2025 Yeouido", date: "", code: "LC_2025_CHERRY_BLOSSOM_FESTIVAL", vfx: false, pokemon: [] },
  { id: "city-safari2023-barcelona-2023", asset: "lc_CitySafari2023_barcelona_2023", series: "citysafari", scope: "regional", en: "City Safari Barcelona", date: "October 13th - 14th 2023", code: "LC_2023_BARCELONA_CITYSAFARI_001", vfx: false, pokemon: [] },
  { id: "city-safari2023-mexico-city-2023", asset: "lc_CitySafari2023_mexicoCity_2023", series: "citysafari", scope: "regional", en: "City Safari Mexico City", date: "November 4th - 5th 2023", code: "LC_2023_MEXICOCITY_CITYSAFARI_001", vfx: false, pokemon: [] },
  { id: "city-safari2023-seoul-2023", asset: "lc_CitySafari2023_seoul_2023", series: "citysafari", scope: "regional", en: "City Safari Seoul", date: "October 7th - 8th 2023", code: "LC_2023_SEOUL_CITYSAFARI_001", vfx: false, pokemon: [] },
  { id: "city-safari2024-hongkong", asset: "lc_CitySafari2024_hongkong", series: "citysafari", scope: "regional", en: "City Safari Hong Kong", date: "December 7th - 8th 2024", code: "LC_2024_HONGKONG_CITYSAFARI_001", vfx: false, pokemon: [] },
  { id: "city-safari2024-incheon", asset: "lc_CitySafari2024_incheon", series: "citysafari", scope: "regional", en: "Safari Zone Incheon", date: "September 27th - 29th 2024", code: "LC_2024_INCHEON_SAFARI_ZONE_001", vfx: false, pokemon: [] },
  { id: "city-safari2024-milan", asset: "lc_CitySafari2024_milan", series: "citysafari", scope: "regional", en: "City Safari Milan", date: "March 29th - 30th 2025", code: "LC_2024_MILAN_CITYSAFARI_001", vfx: false, pokemon: [] },
  { id: "city-safari2024-mumbai", asset: "lc_CitySafari2024_mumbai", series: "citysafari", scope: "regional", en: "City Safari Mumbai", date: "March 29th - 30th 2025", code: "LC_2024_MUMBAI_CITYSAFARI_001", vfx: false, pokemon: [] },
  { id: "city-safari2024-santiago", asset: "lc_CitySafari2024_santiago", series: "citysafari", scope: "regional", en: "City Safari Santiago", date: "March 29th - 30th 2025", code: "LC_2024_SANTIAGO_CITYSAFARI_001", vfx: false, pokemon: [] },
  { id: "city-safari2024-saopaulo", asset: "lc_CitySafari2024_saopaulo", series: "citysafari", scope: "regional", en: "City Safari Sao Paulo", date: "December 7th - 8th 2024", code: "LC_2024_SAOPAULO_CITYSAFARI_001", vfx: false, pokemon: [] },
  { id: "city-safari2024-singapore", asset: "lc_CitySafari2024_singapore", series: "citysafari", scope: "regional", en: "City Safari Singapore", date: "March 29th - 30th 2025", code: "LC_2024_SINGAPORE_CITYSAFARI_001", vfx: false, pokemon: [] },
  { id: "city-safari2024-tainan", asset: "lc_CitySafari2024_tainan", series: "citysafari", scope: "regional", en: "City Safari Tainan", date: "May 11th - 12th 2024", code: "LC_2024_TAINAN_CITYSAFARI_001", vfx: false, pokemon: [] },
  { id: "city-safari2025-amsterdam", asset: "lc_CitySafari2025_amsterdam", series: "citysafari", scope: "regional", en: "City Safari Amsterdam", date: "September 13th-14th 2025", code: "LC_2025_AMSTERDAM_CITYSAFARI_001", vfx: false, pokemon: [] },
  { id: "city-safari2025-bangkok", asset: "lc_CitySafari2025_bangkok", series: "citysafari", scope: "regional", en: "City Safari Bangkok", date: "September 13th-14th 2025", code: "LC_2025_BANGKOK_CITYSAFARI_001", vfx: false, pokemon: [] },
  { id: "city-safari2025-buenos-aires", asset: "lc_CitySafari2025_buenosAires", series: "citysafari", scope: "regional", en: "City Safari2025 Buenos Aires", date: "", code: "LC_CITYSAFARI2025_BUENOSAIRES", vfx: false, pokemon: [] },
  { id: "city-safari2025-cancun", asset: "lc_CitySafari2025_cancun", series: "citysafari", scope: "regional", en: "City Safari Cancun", date: "September 13th-14th 2025", code: "LC_2025_CANCUN_CITYSAFARI_001", vfx: false, pokemon: [] },
  { id: "city-safari2025-miami", asset: "lc_CitySafari2025_miami", series: "citysafari", scope: "regional", en: "City Safari Miami", date: "December 14th 2025", code: "LC_CITYSAFARI2025_MIAMI", vfx: false, pokemon: [] },
  { id: "city-safari2025-sydney", asset: "lc_CitySafari2025_sydney", series: "citysafari", scope: "regional", en: "City Safari Sydney", date: "December 14th 2025", code: "LC_CITYSAFARI2025_SYDNEY", vfx: false, pokemon: [] },
  { id: "city-safari2025-valencia", asset: "lc_CitySafari2025_valencia", series: "citysafari", scope: "regional", en: "City Safari Valencia", date: "September 13th-14th 2025", code: "LC_2025_VALENCIA_CITYSAFARI_001", vfx: false, pokemon: [] },
  { id: "city-safari2025-vancouver", asset: "lc_CitySafari2025_vancouver", series: "citysafari", scope: "regional", en: "City Safari Vancouver", date: "September 13th-14th 2025", code: "LC_2025_VANCOUVER_CITYSAFARI_001", vfx: false, pokemon: [] },
  { id: "lc-gowa-fukuoka", asset: "lc_GOWA_fukuoka", series: "gowa", scope: "regional", en: "GO Wild Area Fukuoka", date: "November 16th - 17th 2024", code: "LC_2024_FUKUOKA_GOWA_001", vfx: false, pokemon: [] },
  { id: "go-fest2023-london", asset: "lc_GoFest2023_london", series: "gofest", scope: "regional", en: "GO Fest London", date: "August 4th - August 6th 2023", code: "LC_2023_LONDON_GOFEST_001", vfx: false, pokemon: [] },
  { id: "go-fest2023-newyork", asset: "lc_GoFest2023_newyork", series: "gofest", scope: "regional", en: "GO Fest New York City", date: "August 18th - August 20th 2023", code: "LC_2023_NYC_GOFEST_001", vfx: false, pokemon: [] },
  { id: "go-fest2023-osaka", asset: "lc_GoFest2023_osaka", series: "gofest", scope: "regional", en: "GO Fest Osaka", date: "August 4th - August 6th 2023", code: "LC_2023_OSAKA_GOFEST_001", vfx: false, pokemon: [] },
  { id: "go-fest2024-madrid", asset: "lc_GoFest2024_madrid", series: "gofest", scope: "regional", en: "GO Fest Madrid", date: "June 14th - 16th 2024", code: "LC_2024_MADRID_GOFEST_001", vfx: false, pokemon: [] },
  { id: "go-fest2024-newyork", asset: "lc_GoFest2024_newyork", series: "gofest", scope: "regional", en: "GO Fest New York City 2024", date: "July 5th - 7th 2024", code: "LC_2024_NYC_GOFEST_001", vfx: false, pokemon: [] },
  { id: "go-fest2024-sendai", asset: "lc_GoFest2024_sendai", series: "gofest", scope: "regional", en: "GO Fest Sendai", date: "May 30th 2024 - June 2nd 2024", code: "LC_2024_SENDAI_GOFEST_001", vfx: false, pokemon: [] },
  { id: "go-fest2025-jerseycity", asset: "lc_GoFest2025_jerseycity", series: "gofest", scope: "regional", en: "GO Fest 2025 Jersey City", date: "June 6th - June 8th 2025", code: "LC_2025_JERSEYCITY_GOFEST_001", vfx: false, pokemon: [] },
  { id: "go-fest2025-osaka", asset: "lc_GoFest2025_osaka", series: "gofest", scope: "regional", en: "GO Fest 2025 Osaka", date: "May 29th - June 1st 2025", code: "LC_2025_OSAKA_GOFEST_001", vfx: false, pokemon: [] },
  { id: "go-fest2025-paris", asset: "lc_GoFest2025_paris", series: "gofest", scope: "regional", en: "GO Fest 2025 Paris", date: "June 13th - June 15th 2025 September 13th-14th 2025", code: "LC_2025_PARIS_GOFEST_001", vfx: false, pokemon: [] },
  { id: "go-fest2026-chicago", asset: "lc_GoFest2026_chicago", series: "gofest", scope: "regional", en: "GO Fest 2026 Chicago", date: "June 5th - 7th 2026", code: "LC_2026_CHICAGO_GOFEST_001", vfx: false, pokemon: [] },
  { id: "go-fest2026-copenhagen", asset: "lc_GoFest2026_copenhagen", series: "gofest", scope: "regional", en: "GO Fest 2026 Copenhagen", date: "June 12th - 14th 2026", code: "LC_2026_COPENHAGEN_GOFEST_001", vfx: false, pokemon: [] },
  { id: "go-fest2026-tokyo", asset: "lc_GoFest2026_tokyo", series: "gofest", scope: "regional", en: "GO Fest 2026 Tokyo", date: "May 28th - May 31st 2026", code: "LC_2026_TOKYO_GOFEST_001", vfx: false, pokemon: [] },
  { id: "go-tour2023", asset: "lc_GoTour2023", series: "gotour", scope: "regional", en: "GO Tour Las Vegas", date: "February 18th - 19th 2023", code: "LC_2023_LASVEGAS_GOTOUR_001", vfx: false, pokemon: [] },
  { id: "go-tour2024-los-angeles", asset: "lc_GoTour2024_losAngeles", series: "gotour", scope: "regional", en: "GO Tour Los Angeles", date: "February 17th - 18th 2024", code: "LC_2024_LOSANGELES_GOTOUR_001", vfx: false, pokemon: [] },
  { id: "go-tour2025-los-angeles", asset: "lc_GoTour2025_losAngeles", series: "gotour", scope: "regional", en: "Go Tour2025 Los Angeles", date: "", code: "LC_2025_LOSANGELES_GOTOUR_001", vfx: false, pokemon: [] },
  { id: "go-tour2025-new-taipei-city", asset: "lc_GoTour2025_newTaipeiCity", series: "gotour", scope: "regional", en: "GO Tour New Taipei City", date: "February 21st - 23rd 2025", code: "LC_2025_NEWTAIPEICITY_GOTOUR_001", vfx: false, pokemon: [] },
  { id: "go-tour2026-los-angeles", asset: "lc_GoTour2026_losAngeles", series: "gotour", scope: "regional", en: "GO Tour 2026 Los Angeles", date: "February 21st - 22nd 2026", code: "LC_2026_LOSANGELES_GOTOUR_001", vfx: false, pokemon: [] },
  { id: "go-tour2026-tainan", asset: "lc_GoTour2026_tainan", series: "gotour", scope: "regional", en: "GO Tour 2026 Tainan", date: "February 21st - 22nd 2026", code: "LC_2026_TAINAN_GOTOUR_001", vfx: false, pokemon: [] },
  { id: "id-car-free-day", asset: "lc_ID_CarFreeDay", series: "lcmisc", scope: "regional", en: "Car Free Day", date: "January 10th - February 211st", code: "LC_ID_CAR_FREE_DAY", vfx: false, pokemon: [] },
  { id: "jangheung-water-festival-2025", asset: "lc_Jangheung_Water_Festival_2025", series: "lcmisc", scope: "regional", en: "Jangheung Water Festival", date: "July 28th - August 3rd 2025", code: "LC_2025_JANGHEUNG_SUMMER_FESTIVAL", vfx: false, pokemon: [] },
  { id: "jeju-air-adv2023", asset: "lc_JejuAirAdv2023", series: "airadv", scope: "regional", en: "Jeju Air Adv2023", date: "", code: "LC_2023_JEJU_AIRADVENTURES_001", vfx: false, pokemon: [] },
  { id: "lotte-giants", asset: "lc_LotteGiants", series: "kbo", scope: "regional", en: "Lotte Giants", date: "June 19th - June 21st 2025", code: "LC_SPECIALBACKGROUND_KR2025_LOTTE_01", vfx: false, pokemon: [] },
  { id: "mlb-arizona-diamondbacks", asset: "lc_MLB_arizonaDiamondbacks", series: "mlb", scope: "regional", en: "Arizona Diamond Backs", date: "August 10th 2025", code: "LC_2024_MLB_007", vfx: false, pokemon: [] },
  { id: "mlb-baltimore-orioles", asset: "lc_MLB_baltimoreOrioles", series: "mlb", scope: "regional", en: "Baltimore Orioles", date: "August 13th 2025", code: "LC_2024_MLB_009", vfx: false, pokemon: [] },
  { id: "mlb-boston-red-sox", asset: "lc_MLB_bostonRedSox", series: "mlb", scope: "regional", en: "Boston Red Sox", date: "August 29th 2025", code: "LC_2024_MLB_012", vfx: false, pokemon: [] },
  { id: "mlb-chicago-whitesox", asset: "lc_MLB_chicagoWhitesox", series: "mlb", scope: "regional", en: "Chicago White Sox", date: "August 11th 2025", code: "LC_2024_MLB_008", vfx: false, pokemon: [] },
  { id: "mlb-cleveland-guardians", asset: "lc_MLB_clevelandGuardians", series: "mlb", scope: "regional", en: "Cleveland Guardians", date: "August 14th 2025", code: "LC_2024_MLB_003", vfx: false, pokemon: [] },
  { id: "mlb-mariners", asset: "lc_MLB_mariners", series: "mlb", scope: "regional", en: "MLB Mariners", date: "September 12th 2024", code: "LC_2024_MLB_002", vfx: false, pokemon: [] },
  { id: "mlb-marlins", asset: "lc_MLB_marlins", series: "mlb", scope: "regional", en: "MLB Marlins", date: "September 7th 2024", code: "LC_2024_MLB_001", vfx: false, pokemon: [] },
  { id: "mlb-milwaukee-brewers", asset: "lc_MLB_milwaukeeBrewers", series: "mlb", scope: "regional", en: "Milwaukee Brewers", date: "July 25th 2025", code: "LC_2024_MLB_005", vfx: false, pokemon: [] },
  { id: "mlb-minnesota-twins", asset: "lc_MLB_minnesotaTwins", series: "mlb", scope: "regional", en: "Minnesota Twins", date: "August 31st 2025", code: "LC_2024_MLB_013", vfx: false, pokemon: [] },
  { id: "mlb-newyork-mets", asset: "lc_MLB_newyorkMets", series: "mlb", scope: "regional", en: "New York Mets", date: "August 25th 2025", code: "LC_2024_MLB_010", vfx: false, pokemon: [] },
  { id: "mlb-san-francisco-giants", asset: "lc_MLB_sanFranciscoGiants", series: "mlb", scope: "regional", en: "San Francisco Giants", date: "August 29th 2025", code: "LC_2024_MLB_011", vfx: false, pokemon: [] },
  { id: "mlb-tampa-bay-rays", asset: "lc_MLB_tampaBayRays", series: "mlb", scope: "regional", en: "Tampa Bay Rays", date: "July 20th 2025", code: "LC_2024_MLB_004", vfx: false, pokemon: [] },
  { id: "mlb-tampa-bay-rays2", asset: "lc_MLB_tampaBayRays2", series: "mlb", scope: "regional", en: "Tampa Bay Rays", date: "July 20th 2025", code: "LC_2026_MLB_TBRAYS", vfx: false, pokemon: [] },
  { id: "mlb-texas-rangers", asset: "lc_MLB_texasRangers", series: "mlb", scope: "regional", en: "Texas Rangers", date: "September 7th 2025", code: "LC_2024_MLB_014", vfx: false, pokemon: [] },
  { id: "mlb-washington-nationals", asset: "lc_MLB_washingtonNationals", series: "mlb", scope: "regional", en: "Washington Nationals", date: "August 5th 2025", code: "LC_2024_MLB_006", vfx: false, pokemon: [] },
  { id: "nfl-cardinals", asset: "lc_NFL_cardinals", series: "nfl", scope: "regional", en: "NFL Cardinals", date: "December 21st", code: "LC_2025_NFL_001", vfx: false, pokemon: [] },
  { id: "osaka-event2025-01", asset: "lc_OsakaEvent2025_01", series: "osaka2025", scope: "regional", en: "Osaka Event2025 01", date: "", code: "LC_2025_OSAKA_EVENT_001", vfx: false, pokemon: [] },
  { id: "osaka-event2025-02", asset: "lc_OsakaEvent2025_02", series: "osaka2025", scope: "regional", en: "Osaka Event2025 02", date: "", code: "LC_2025_OSAKA_EVENT_002", vfx: false, pokemon: [] },
  { id: "osaka-event2025-03", asset: "lc_OsakaEvent2025_03", series: "osaka2025", scope: "regional", en: "Osaka Event2025 03", date: "", code: "LC_2025_OSAKA_EVENT_003", vfx: false, pokemon: [] },
  { id: "paris2025-01", asset: "lc_Paris2025_01", series: "paris2025", scope: "regional", en: "Paris2025 01", date: "", code: "LC_2025_PARIS_001", vfx: false, pokemon: [] },
  { id: "paris2025-02", asset: "lc_Paris2025_02", series: "paris2025", scope: "regional", en: "Paris2025 02", date: "", code: "LC_2025_PARIS_002", vfx: false, pokemon: [] },
  { id: "tok-mun-koto", asset: "lc_TokMun_koto", series: "tokmun", scope: "regional", en: "Tok Mun Koto", date: "", code: "LC_TOKMUN_STAMP_02", vfx: false, pokemon: [] },
  { id: "tok-mun-minato", asset: "lc_TokMun_minato", series: "tokmun", scope: "regional", en: "Tok Mun Minato", date: "", code: "LC_TOKMUN_STAMP_03", vfx: false, pokemon: [] },
  { id: "tok-mun-shinagawa", asset: "lc_TokMun_shinagawa", series: "tokmun", scope: "regional", en: "Tok Mun Shinagawa", date: "", code: "LC_TOKMUN_STAMP_01", vfx: false, pokemon: [] },
  { id: "wcs2024-honolulu", asset: "lc_Wcs2024_honolulu", series: "wcs", scope: "regional", en: "2024 Pokemon World Championships", date: "August 16th - 18th 2024", code: "", vfx: false, pokemon: [] },
  { id: "wcs2025-anaheim", asset: "lc_Wcs2025_anaheim", series: "wcs", scope: "regional", en: "2025 Pokemon World Championships", date: "August 15th - 17th 2025", code: "LC_2025_ANAHEIM_WORLD_CHAMPIONSHIPS_001", vfx: false, pokemon: [] },
  { id: "wcs2026-san-francisco", asset: "lc_Wcs2026_sanFrancisco", series: "wcs", scope: "regional", en: "Wcs2026 San Francisco", date: "", code: "LC_2026_SANFRANCISCO_WCS_001", vfx: false, pokemon: [] },
  { id: "busan-fireworks-festival-2025", asset: "lc_busanFireworksFestival_2025", series: "lcmisc", scope: "regional", en: "Busan Fireworks Festival", date: "??", code: "", vfx: false, pokemon: [] },
  { id: "carnival-flamigo-cologne-2026", asset: "lc_carnivalFlamigo_cologne_2026", series: "carnival", scope: "regional", en: "Carnival Flamigo Cologne", date: "February 3rd - 8th 2026", code: "LC_2026_COLOGNE_CARNIVAL_001", vfx: false, pokemon: [] },
  { id: "carnival-flamigo-rio-2026", asset: "lc_carnivalFlamigo_rio_2026", series: "carnival", scope: "regional", en: "Carnival Flamigo Rio", date: "February 3rd - 8th 2026", code: "LC_2026_RIODEJANEIRO_CARNIVAL_001", vfx: false, pokemon: [] },
  { id: "nagasaki2025", asset: "lc_nagasaki2025", series: "lcmisc", scope: "regional", en: "Nagasaki2025", date: "", code: "LC_2025_GOWA_NAGASAKI", vfx: false, pokemon: [] },
  { id: "national-trust-anglesey-abbey", asset: "lc_nationalTrust_angleseyAbbey", series: "nationaltrust", scope: "regional", en: "National Trust Anglesey Abbey", date: "July 18th - September 6th 2026", code: "LC_NT_1", vfx: false, pokemon: [] },
  { id: "national-trust-attinghampark", asset: "lc_nationalTrust_attinghampark", series: "nationaltrust", scope: "regional", en: "National Trust Attingham Park", date: "July 18th - September 6th 2026", code: "LC_NT_2", vfx: false, pokemon: [] },
  { id: "national-trust-belton-house", asset: "lc_nationalTrust_beltonHouse", series: "nationaltrust", scope: "regional", en: "National Trust Belton House", date: "July 18th - September 6th 2026", code: "LC_NT_3", vfx: false, pokemon: [] },
  { id: "national-trust-calke-abbey", asset: "lc_nationalTrust_calkeAbbey", series: "nationaltrust", scope: "regional", en: "National Trust Calke Abbey", date: "July 18th - September 6th 2026", code: "LC_NT_4", vfx: false, pokemon: [] },
  { id: "national-trust-chirk", asset: "lc_nationalTrust_chirk", series: "nationaltrust", scope: "regional", en: "National Trust Chirk", date: "July 18th - September 6th 2026", code: "LC_NT_5", vfx: false, pokemon: [] },
  { id: "national-trust-cliveden", asset: "lc_nationalTrust_cliveden", series: "nationaltrust", scope: "regional", en: "National Trust Cliveden", date: "July 18th - September 6th 2026", code: "LC_NT_6", vfx: false, pokemon: [] },
  { id: "national-trust-clumber-park", asset: "lc_nationalTrust_clumberPark", series: "nationaltrust", scope: "regional", en: "National Trust Clumber Park", date: "July 18th - September 6th 2026", code: "LC_NT_7", vfx: false, pokemon: [] },
  { id: "national-trust-dunham-massey", asset: "lc_nationalTrust_dunhamMassey", series: "nationaltrust", scope: "regional", en: "National Trust Dunham Massey", date: "July 18th - September 6th 2026", code: "LC_NT_8", vfx: false, pokemon: [] },
  { id: "national-trust-fountains-abbey-estate", asset: "lc_nationalTrust_fountainsAbbeyEstate", series: "nationaltrust", scope: "regional", en: "National Trust Fountains Abbey Estate", date: "July 18th - September 6th 2026", code: "LC_NT_9", vfx: false, pokemon: [] },
  { id: "national-trust-gibslide", asset: "lc_nationalTrust_gibslide", series: "nationaltrust", scope: "regional", en: "National Trust Gibslide", date: "", code: "LC_NT_10", vfx: false, pokemon: [] },
  { id: "national-trust-hanbury", asset: "lc_nationalTrust_hanbury", series: "nationaltrust", scope: "regional", en: "National Trust Hanbury", date: "July 18th - September 6th 2026", code: "LC_NT_11", vfx: false, pokemon: [] },
  { id: "national-trust-hardwick", asset: "lc_nationalTrust_hardwick", series: "nationaltrust", scope: "regional", en: "National Trust Hardwick", date: "July 18th - September 6th 2026", code: "LC_NT_12", vfx: false, pokemon: [] },
  { id: "national-trust-killerton", asset: "lc_nationalTrust_killerton", series: "nationaltrust", scope: "regional", en: "National Trust Killerton", date: "July 18th - September 6th 2026", code: "LC_NT_13", vfx: false, pokemon: [] },
  { id: "national-trust-kingston-lacy", asset: "lc_nationalTrust_kingstonLacy", series: "nationaltrust", scope: "regional", en: "National Trust Kingston Lacy", date: "July 18th - September 6th 2026", code: "LC_NT_14", vfx: false, pokemon: [] },
  { id: "national-trust-lacock", asset: "lc_nationalTrust_lacock", series: "nationaltrust", scope: "regional", en: "National Trust Lacock", date: "July 18th - September 6th 2026", code: "LC_NT_15", vfx: false, pokemon: [] },
  { id: "national-trust-lyme-park", asset: "lc_nationalTrust_lymePark", series: "nationaltrust", scope: "regional", en: "National Trust Lyme Park", date: "July 18th - September 6th 2026", code: "LC_NT_16", vfx: false, pokemon: [] },
  { id: "national-trust-mottisfont", asset: "lc_nationalTrust_mottisfont", series: "nationaltrust", scope: "regional", en: "National Trust Mottisfont", date: "July 18th - September 6th 2026", code: "LC_NT_17", vfx: false, pokemon: [] },
  { id: "national-trust-mount-stewart", asset: "lc_nationalTrust_mountStewart", series: "nationaltrust", scope: "regional", en: "National Trust Mount Stewart", date: "July 18th - September 6th 2026", code: "LC_NT_18", vfx: false, pokemon: [] },
  { id: "national-trust-nymans", asset: "lc_nationalTrust_nymans", series: "nationaltrust", scope: "regional", en: "National Trust Nymans", date: "July 18th - September 6th 2026", code: "LC_NT_19", vfx: false, pokemon: [] },
  { id: "national-trust-polesden", asset: "lc_nationalTrust_polesden", series: "nationaltrust", scope: "regional", en: "National Trust Polesden", date: "July 18th - September 6th 2026", code: "LC_NT_20", vfx: false, pokemon: [] },
  { id: "national-trust-scotney-castle", asset: "lc_nationalTrust_scotneyCastle", series: "nationaltrust", scope: "regional", en: "National Trust Scotney Castle", date: "July 18th - September 6th 2026", code: "LC_NT_21", vfx: false, pokemon: [] },
  { id: "national-trust-stourhead", asset: "lc_nationalTrust_stourhead", series: "nationaltrust", scope: "regional", en: "National Trust Stourhead", date: "July 18th - September 6th 2026", code: "LC_NT_22", vfx: false, pokemon: [] },
  { id: "national-trust-stowe-garden-park", asset: "lc_nationalTrust_stoweGardenPark", series: "nationaltrust", scope: "regional", en: "National Trust Stowe Garden Park", date: "July 18th - September 6th 2026", code: "LC_NT_23", vfx: false, pokemon: [] },
  { id: "national-trust-tredegar-house", asset: "lc_nationalTrust_tredegarHouse", series: "nationaltrust", scope: "regional", en: "National Trust Tredegar House", date: "July 18th - September 6th 2026", code: "LC_NT_24", vfx: false, pokemon: [] },
  { id: "national-trust-trelissick", asset: "lc_nationalTrust_trelissick", series: "nationaltrust", scope: "regional", en: "National Trust Trelissick", date: "July 18th - September 6th 2026", code: "LC_NT_25", vfx: false, pokemon: [] },
  { id: "national-trust-tyntesfield", asset: "lc_nationalTrust_tyntesfield", series: "nationaltrust", scope: "regional", en: "National Trust Tyntesfield", date: "July 18th - September 6th 2026", code: "LC_NT_26", vfx: false, pokemon: [] },
  { id: "national-trust-whimpole", asset: "lc_nationalTrust_whimpole", series: "nationaltrust", scope: "regional", en: "National Trust Whimpole", date: "", code: "LC_NT_27", vfx: false, pokemon: [] },
  { id: "pokecenter-golab", asset: "lc_pokecenter_GOLab", series: "pokecenter", scope: "regional", en: "Pokemon Center GO Lab", date: "July 1st 2026 - August 31st 2027", code: "LC_JAPAN_STAMP_RALLY_18", vfx: false, pokemon: [] },
  { id: "pokecenter-fukuoka", asset: "lc_pokecenter_fukuoka", series: "pokecenter", scope: "regional", en: "Pokemon Center Fukuoka", date: "July 1st 2026 - August 31st 2027", code: "LC_JAPAN_STAMP_RALLY_16", vfx: false, pokemon: [] },
  { id: "pokecenter-hiroshima", asset: "lc_pokecenter_hiroshima", series: "pokecenter", scope: "regional", en: "Pokemon Center Hiroshima", date: "July 1st 2026 - August 31st 2027", code: "LC_JAPAN_STAMP_RALLY_14", vfx: false, pokemon: [] },
  { id: "pokecenter-kagawa", asset: "lc_pokecenter_kagawa", series: "pokecenter", scope: "regional", en: "Pokemon Center Kagawa", date: "July 1st 2026 - August 31st 2027", code: "LC_JAPAN_STAMP_RALLY_15", vfx: false, pokemon: [] },
  { id: "pokecenter-kanazawa", asset: "lc_pokecenter_kanazawa", series: "pokecenter", scope: "regional", en: "Pokemon Center Kanazawa", date: "July 1st 2026 - August 31st 2027", code: "LC_JAPAN_STAMP_RALLY_10", vfx: false, pokemon: [] },
  { id: "pokecenter-kyoto", asset: "lc_pokecenter_kyoto", series: "pokecenter", scope: "regional", en: "Pokemon Center Kyoto", date: "July 1st 2026 - August 31st 2027", code: "LC_JAPAN_STAMP_RALLY_11", vfx: false, pokemon: [] },
  { id: "pokecenter-mega-tokyo", asset: "lc_pokecenter_megaTokyo", series: "pokecenter", scope: "regional", en: "Pokemon Center Mega Tokyo", date: "July 1st 2026 - August 31st 2027", code: "LC_JAPAN_STAMP_RALLY_4", vfx: false, pokemon: [] },
  { id: "pokecenter-nagoya", asset: "lc_pokecenter_nagoya", series: "pokecenter", scope: "regional", en: "Pokemon Center Nagoya", date: "July 1st 2026 - August 31st 2027", code: "LC_JAPAN_STAMP_RALLY_9", vfx: false, pokemon: [] },
  { id: "pokecenter-okinawa", asset: "lc_pokecenter_okinawa", series: "pokecenter", scope: "regional", en: "Pokemon Center Okinawa", date: "July 1st 2026 - August 31st 2027", code: "LC_JAPAN_STAMP_RALLY_17", vfx: false, pokemon: [] },
  { id: "pokecenter-osaka", asset: "lc_pokecenter_osaka", series: "pokecenter", scope: "regional", en: "Pokemon Center Osaka", date: "July 1st 2026 - August 31st 2027", code: "LC_JAPAN_STAMP_RALLY_13", vfx: false, pokemon: [] },
  { id: "pokecenter-osaka-dx", asset: "lc_pokecenter_osakaDX", series: "pokecenter", scope: "regional", en: "Pokemon Center Osaka DX", date: "July 1st 2026 - August 31st 2027", code: "LC_JAPAN_STAMP_RALLY_12", vfx: false, pokemon: [] },
  { id: "pokecenter-sapporo", asset: "lc_pokecenter_sapporo", series: "pokecenter", scope: "regional", en: "Pokemon Center Sapporo", date: "July 1st 2026 - August 31st 2027", code: "LC_JAPAN_STAMP_RALLY_1", vfx: false, pokemon: [] },
  { id: "pokecenter-shibuya", asset: "lc_pokecenter_shibuya", series: "pokecenter", scope: "regional", en: "Pokemon Center Shibuya", date: "July 1st 2026 - August 31st 2027", code: "LC_JAPAN_STAMP_RALLY_5", vfx: false, pokemon: [] },
  { id: "pokecenter-skytree-town", asset: "lc_pokecenter_skytreeTown", series: "pokecenter", scope: "regional", en: "Pokemon Center Skytree Town", date: "July 1st 2026 - August 31st 2027", code: "LC_JAPAN_STAMP_RALLY_6", vfx: false, pokemon: [] },
  { id: "pokecenter-tohoku", asset: "lc_pokecenter_tohoku", series: "pokecenter", scope: "regional", en: "Pokemon Center Tohoku", date: "July 1st 2026 - August 31st 2027", code: "LC_JAPAN_STAMP_RALLY_2", vfx: false, pokemon: [] },
  { id: "pokecenter-tokyo-bay", asset: "lc_pokecenter_tokyoBay", series: "pokecenter", scope: "regional", en: "Pokemon Center Tokyo Bay", date: "July 1st 2026 - August 31st 2027", code: "LC_JAPAN_STAMP_RALLY_7", vfx: false, pokemon: [] },
  { id: "pokecenter-tokyo-dx", asset: "lc_pokecenter_tokyoDX", series: "pokecenter", scope: "regional", en: "Pokemon Center Tokyo DX", date: "July 1st 2026 - August 31st 2027", code: "LC_JAPAN_STAMP_RALLY_3", vfx: false, pokemon: [] },
  { id: "pokecenter-yokohama", asset: "lc_pokecenter_yokohama", series: "pokecenter", scope: "regional", en: "Pokecenter Yokohama", date: "", code: "LC_JAPAN_STAMP_RALLY_8", vfx: false, pokemon: [] },
  { id: "pokelid-aichi", asset: "lc_pokelid_aichi", series: "pokelid", scope: "regional", en: "Pokelid Aichi", date: "2026", code: "LC_POKELID_AICHI", vfx: false, pokemon: [] },
  { id: "pokelid-akita", asset: "lc_pokelid_akita", series: "pokelid", scope: "regional", en: "Pokelid Akita", date: "2026", code: "LC_POKELID_AKITA", vfx: false, pokemon: [] },
  { id: "pokelid-aomori", asset: "lc_pokelid_aomori", series: "pokelid", scope: "regional", en: "Pokelid Aomori", date: "2026", code: "LC_POKELID_AOMORI", vfx: false, pokemon: [] },
  { id: "pokelid-chiba", asset: "lc_pokelid_chiba", series: "pokelid", scope: "regional", en: "Pokelid Chiba", date: "2026", code: "LC_POKELID_CHIBA", vfx: false, pokemon: [] },
  { id: "pokelid-ehime", asset: "lc_pokelid_ehime", series: "pokelid", scope: "regional", en: "Pokelid Ehime", date: "2026", code: "LC_POKELID_EHIME", vfx: false, pokemon: [] },
  { id: "pokelid-fukui", asset: "lc_pokelid_fukui", series: "pokelid", scope: "regional", en: "Pokelid Fukui", date: "2026", code: "LC_POKELID_FUKUI", vfx: false, pokemon: [] },
  { id: "pokelid-fukuoka", asset: "lc_pokelid_fukuoka", series: "pokelid", scope: "regional", en: "Pokelid Fukuoka", date: "November 7th 2025", code: "LC_POKELID_FUKUOKA", vfx: false, pokemon: [] },
  { id: "pokelid-fukushima", asset: "lc_pokelid_fukushima", series: "pokelid", scope: "regional", en: "Pokelid Fukushima", date: "2026", code: "LC_POKELID_FUKUSHIMA", vfx: false, pokemon: [] },
  { id: "pokelid-gifu", asset: "lc_pokelid_gifu", series: "pokelid", scope: "regional", en: "Pokelid Gifu", date: "2026", code: "LC_POKELID_GIFU", vfx: false, pokemon: [] },
  { id: "pokelid-hokkaido", asset: "lc_pokelid_hokkaido", series: "pokelid", scope: "regional", en: "Pokelid Hokkaido", date: "2026", code: "LC_POKELID_HOKKAIDO", vfx: false, pokemon: [] },
  { id: "pokelid-hyogo", asset: "lc_pokelid_hyogo", series: "pokelid", scope: "regional", en: "Pokelid Hyogo", date: "2026", code: "LC_POKELID_HYOGO", vfx: false, pokemon: [] },
  { id: "pokelid-ibaraki", asset: "lc_pokelid_ibaraki", series: "pokelid", scope: "regional", en: "Pokelid Ibaraki", date: "2026", code: "LC_POKELID_IBARAKI", vfx: false, pokemon: [] },
  { id: "pokelid-ishikawa", asset: "lc_pokelid_ishikawa", series: "pokelid", scope: "regional", en: "Pokelid Ishikawa", date: "2026", code: "LC_POKELID_ISHIKAWA", vfx: false, pokemon: [] },
  { id: "pokelid-iwate", asset: "lc_pokelid_iwate", series: "pokelid", scope: "regional", en: "Pokelid Iwate", date: "2026", code: "LC_POKELID_IWATE", vfx: false, pokemon: [] },
  { id: "pokelid-kagawa", asset: "lc_pokelid_kagawa", series: "pokelid", scope: "regional", en: "Pokelid Kagawa", date: "2026", code: "LC_POKELID_KAGAWA", vfx: false, pokemon: [] },
  { id: "pokelid-kagoshima", asset: "lc_pokelid_kagoshima", series: "pokelid", scope: "regional", en: "Pokelid Kagoshima", date: "November 7th 2025", code: "LC_POKELID_KAGOSHIMA", vfx: false, pokemon: [] },
  { id: "pokelid-kanagawa", asset: "lc_pokelid_kanagawa", series: "pokelid", scope: "regional", en: "Pokelid Kanagawa", date: "2026", code: "LC_POKELID_KANAGAWA", vfx: false, pokemon: [] },
  { id: "pokelid-kochi", asset: "lc_pokelid_kochi", series: "pokelid", scope: "regional", en: "Pokelid Kochi", date: "2026", code: "LC_POKELID_KOCHI", vfx: false, pokemon: [] },
  { id: "pokelid-kyoto", asset: "lc_pokelid_kyoto", series: "pokelid", scope: "regional", en: "Pokelid Kyoto", date: "2026", code: "LC_POKELID_KYOTO", vfx: false, pokemon: [] },
  { id: "pokelid-mie", asset: "lc_pokelid_mie", series: "pokelid", scope: "regional", en: "Pokelid Mie", date: "2026", code: "LC_POKELID_MIE", vfx: false, pokemon: [] },
  { id: "pokelid-miyagi", asset: "lc_pokelid_miyagi", series: "pokelid", scope: "regional", en: "Pokelid Miyagi", date: "2026", code: "LC_POKELID_MIYAGI", vfx: false, pokemon: [] },
  { id: "pokelid-miyazaki", asset: "lc_pokelid_miyazaki", series: "pokelid", scope: "regional", en: "Pokelid Miyazaki", date: "November 7th 2025", code: "LC_POKELID_MIYAZAKI", vfx: false, pokemon: [] },
  { id: "pokelid-nagasaki", asset: "lc_pokelid_nagasaki", series: "pokelid", scope: "regional", en: "Pokelid Nagasaki", date: "November 7th 2025", code: "LC_POKELID_NAGASAKI", vfx: false, pokemon: [] },
  { id: "pokelid-nara", asset: "lc_pokelid_nara", series: "pokelid", scope: "regional", en: "Pokelid Nara", date: "2026", code: "LC_POKELID_NARA", vfx: false, pokemon: [] },
  { id: "pokelid-niigata", asset: "lc_pokelid_niigata", series: "pokelid", scope: "regional", en: "Pokelid Niigata", date: "2026", code: "LC_POKELID_NIIGATA", vfx: false, pokemon: [] },
  { id: "pokelid-okayama", asset: "lc_pokelid_okayama", series: "pokelid", scope: "regional", en: "Pokelid Okayama", date: "2026", code: "LC_POKELID_OKAYAMA", vfx: false, pokemon: [] },
  { id: "pokelid-okinawa", asset: "lc_pokelid_okinawa", series: "pokelid", scope: "regional", en: "Pokelid Okinawa", date: "November 7th 2025", code: "LC_POKELID_OKINAWA", vfx: false, pokemon: [] },
  { id: "pokelid-osaka", asset: "lc_pokelid_osaka", series: "pokelid", scope: "regional", en: "Pokelid Osaka", date: "2026", code: "LC_POKELID_OSAKA", vfx: false, pokemon: [] },
  { id: "pokelid-saga", asset: "lc_pokelid_saga", series: "pokelid", scope: "regional", en: "Pokelid Saga", date: "November 7th 2025", code: "LC_POKELID_SAGA", vfx: false, pokemon: [] },
  { id: "pokelid-saitama", asset: "lc_pokelid_saitama", series: "pokelid", scope: "regional", en: "Pokelid Saitama", date: "2026", code: "LC_POKELID_SAITAMA", vfx: false, pokemon: [] },
  { id: "pokelid-shiga", asset: "lc_pokelid_shiga", series: "pokelid", scope: "regional", en: "Pokelid Shiga", date: "2026", code: "LC_POKELID_SHIGA", vfx: false, pokemon: [] },
  { id: "pokelid-shimane", asset: "lc_pokelid_shimane", series: "pokelid", scope: "regional", en: "Pokelid Shimane", date: "2026", code: "LC_POKELID_SHIMANE", vfx: false, pokemon: [] },
  { id: "pokelid-shizuoka", asset: "lc_pokelid_shizuoka", series: "pokelid", scope: "regional", en: "Pokelid Shizuoka", date: "2026", code: "LC_POKELID_SHIZUOKA", vfx: false, pokemon: [] },
  { id: "pokelid-tochigi", asset: "lc_pokelid_tochigi", series: "pokelid", scope: "regional", en: "Pokelid Tochigi", date: "2026", code: "LC_POKELID_TOCHIGI", vfx: false, pokemon: [] },
  { id: "pokelid-tokushima", asset: "lc_pokelid_tokushima", series: "pokelid", scope: "regional", en: "Pokelid Tokushima", date: "2026", code: "LC_POKELID_TOKUSHIMA", vfx: false, pokemon: [] },
  { id: "pokelid-tokyo", asset: "lc_pokelid_tokyo", series: "pokelid", scope: "regional", en: "Pokelid Tokyo", date: "2026", code: "LC_POKELID_TOKYO", vfx: false, pokemon: [] },
  { id: "pokelid-tottori", asset: "lc_pokelid_tottori", series: "pokelid", scope: "regional", en: "Pokelid Tottori", date: "2026", code: "LC_POKELID_TOTTORI", vfx: false, pokemon: [] },
  { id: "pokelid-toyama", asset: "lc_pokelid_toyama", series: "pokelid", scope: "regional", en: "Pokelid Toyama", date: "2026", code: "LC_POKELID_TOYAMA", vfx: false, pokemon: [] },
  { id: "pokelid-wakayama", asset: "lc_pokelid_wakayama", series: "pokelid", scope: "regional", en: "Pokelid Wakayama", date: "2026", code: "LC_POKELID_WAKAYAMA", vfx: false, pokemon: [] },
  { id: "pokelid-yamagata", asset: "lc_pokelid_yamagata", series: "pokelid", scope: "regional", en: "Pokelid Yamagata", date: "", code: "LC_POKELID_YAMAGATA", vfx: false, pokemon: [] },
  { id: "pokelid-yamaguchi", asset: "lc_pokelid_yamaguchi", series: "pokelid", scope: "regional", en: "Pokelid Yamaguchi", date: "2026", code: "LC_POKELID_YAMAGUCHI", vfx: false, pokemon: [] },
  { id: "pokopia2026", asset: "lc_pokopia2026", series: "lcmisc", scope: "regional", en: "Pokemon Pokopia", date: "March 10th - March 16th 2026", code: "LC_SPECIALBACKGROUND_POK2026", vfx: false, pokemon: [] },
  { id: "roadtrip2025-berlin", asset: "lc_roadtrip2025_berlin", series: "roadtrip", scope: "regional", en: "Road Trip 2025 Berlin", date: "August 9th 2025", code: "LC_2025_BERLIN_ROADTRIP_001", vfx: false, pokemon: [] },
  { id: "roadtrip2025-cologne", asset: "lc_roadtrip2025_cologne", series: "roadtrip", scope: "regional", en: "Road Trip 2025 Cologne", date: "August 20th - 24th 2025", code: "LC_2025_COLOGNE_ROADTRIP_001", vfx: false, pokemon: [] },
  { id: "roadtrip2025-hague", asset: "lc_roadtrip2025_hague", series: "roadtrip", scope: "regional", en: "Roadtrip2025 Hague", date: "", code: "LC_2025_HAGUE_ROADTRIP_001", vfx: false, pokemon: [] },
  { id: "roadtrip2025-london", asset: "lc_roadtrip2025_london", series: "roadtrip", scope: "regional", en: "Road Trip 2025 London", date: "July 19th 2025", code: "LC_2025_LONDON_ROADTRIP_001", vfx: false, pokemon: [] },
  { id: "roadtrip2025-manchester", asset: "lc_roadtrip2025_manchester", series: "roadtrip", scope: "regional", en: "Road Trip 2025 Manchester", date: "July 16th 2025", code: "LC_2025_MANCHESTER_ROADTRIP_001", vfx: false, pokemon: [] },
  { id: "roadtrip2025-paris", asset: "lc_roadtrip2025_paris", series: "roadtrip", scope: "regional", en: "Road Trip 2025 Paris", date: "July 26th 2025", code: "LC_2025_PARIS_ROADTRIP_001", vfx: false, pokemon: [] },
  { id: "roadtrip2025-valencia", asset: "lc_roadtrip2025_valencia", series: "roadtrip", scope: "regional", en: "Road Trip 2025 Valencia", date: "August 2nd 2025", code: "LC_2025_VALENCIA_ROADTRIP_001", vfx: false, pokemon: [] },
  { id: "stamp-rally2025-jeju", asset: "lc_stampRally2025_Jeju", series: "lcmisc", scope: "regional", en: "Stamp Rally2025 Jeju", date: "", code: "LC_JEJU_STAMP_RALLY", vfx: false, pokemon: [] },
  { id: "taipei-amusement-park-2025", asset: "lc_taipeiAmusementPark_2025", series: "lcmisc", scope: "regional", en: "Taipei Amusement Park 2025", date: "", code: "LC_2025_TAIPEICITY_AMUSEMENT_PARK", vfx: false, pokemon: [] },
  { id: "taipei-flower-festival-2026", asset: "lc_taipeiFlowerFestival_2026", series: "lcmisc", scope: "regional", en: "Taipei Flower Festival 2026", date: "", code: "LC_SPECIALBACKGROUND_EXTRA_2025_02", vfx: false, pokemon: [] },
  { id: "tpc30th-malaysia", asset: "lc_tpc30th_malaysia", series: "tpc30th", scope: "regional", en: "Tpc30th Malaysia", date: "", code: "", vfx: false, pokemon: [] },
  { id: "tpc30th-philippines", asset: "lc_tpc30th_philippines", series: "tpc30th", scope: "regional", en: "Tpc30th Philippines", date: "", code: "", vfx: false, pokemon: [] },
  { id: "tpc30th-singapore", asset: "lc_tpc30th_singapore", series: "tpc30th", scope: "regional", en: "Tpc30th Singapore", date: "", code: "", vfx: false, pokemon: [] },
  { id: "tpc30th-taiwan", asset: "lc_tpc30th_taiwan", series: "tpc30th", scope: "regional", en: "Tpc30th Taiwan", date: "", code: "", vfx: false, pokemon: [] },
  { id: "2024-december-cd-recap", asset: "sb_2024_decemberCdRecap", series: "sbmisc", scope: "global", en: "2024 December Cd Recap", date: "", code: "LC_SPECIALBACKGROUND_2024_DECEMBERCDRECAP", vfx: false, pokemon: [] },
  { id: "9th-anniversary", asset: "sb_9thAnniversary", series: "sbmisc", scope: "global", en: "9th Anniversary", date: "", code: "LC_SPECIALBACKGROUND_GG2026", vfx: true, pokemon: [] },
  { id: "community-2026", asset: "sb_Community_2026", series: "sbmisc", scope: "global", en: "Community Day 2026", date: "January 2026 - December 2026", code: "LC_SPECIALBACKGROUND_2026_COMMUNITYDAY", vfx: true, pokemon: [] },
  { id: "concierge2025", asset: "sb_Concierge2025", series: "sbmisc", scope: "global", en: "Pokemon Concierge", date: "September 9th - 14th 2025", code: "LC_SPECIALBACKGROUND_CON2025", vfx: false, pokemon: [] },
  { id: "festivalof-colors-2026", asset: "sb_FestivalofColors_2026", series: "sbmisc", scope: "global", en: "Festival of Colors", date: "March 4th - March 8th 2025", code: "LC_SPECIALBACKGROUND_EXTRA_2025_01", vfx: true, pokemon: [] },
  { id: "gowa2025-global", asset: "sb_GOWA2025_Global", series: "gowa", scope: "global", en: "GO Wild Area 2025", date: "November 15th - 16th 2025", code: "LC_SPECIALBACKGROUND_2025_GOWA_GLOBAL", vfx: true, pokemon: [] },
  { id: "sb-gowa-fukuoka", asset: "sb_GOWA_fukuoka", series: "gowa", scope: "global", en: "GO Wild Area Fukuoka", date: "November 16th - 17th 2024", code: "LC_SPECIALBACKGROUND_2024_GLOBAL_GOWA_001", vfx: false, pokemon: [] },
  { id: "go-fest2024-radiance", asset: "sb_GoFest2024_radiance", series: "gofest", scope: "global", en: "GO Fest 2024 Radiance", date: "July 14th 2024", code: "LC_SPECIALBACKGROUND_2024_GLOBAL_GOFEST_RADIANCE_001", vfx: true, pokemon: [] },
  { id: "go-fest2024-umbra", asset: "sb_GoFest2024_umbra", series: "gofest", scope: "global", en: "GO Fest 2024 Umbra", date: "July 14th 2024", code: "LC_SPECIALBACKGROUND_2024_GLOBAL_GOFEST_UMBRA_001", vfx: true, pokemon: [] },
  { id: "go-fest2024-wormhole", asset: "sb_GoFest2024_wormhole", series: "gofest", scope: "global", en: "GO Fest 2024 Wormhole", date: "July 8th - 14th 2024", code: "LC_SPECIAL_BACKGROUND_2024_GLOBAL_GOFEST_ULTRA_WORMHOLE_001", vfx: true, pokemon: [] },
  { id: "go-fest2024-wormhole-moon", asset: "sb_GoFest2024_wormhole_moon", series: "gofest", scope: "global", en: "GO Fest 2024 Wormhole", date: "July 8th - 14th 2024", code: "LC_SPECIAL_BACKGROUND_2024_GLOBAL_GOFEST_MOON_ULTRA_WORMHOLE_001", vfx: true, pokemon: [] },
  { id: "go-fest2024-wormhole-sun", asset: "sb_GoFest2024_wormhole_sun", series: "gofest", scope: "global", en: "GO Fest 2024 Wormhole", date: "July 8th - 14th 2024", code: "LC_SPECIAL_BACKGROUND_2024_GLOBAL_GOFEST_SUN_ULTRA_WORMHOLE_001", vfx: true, pokemon: [] },
  { id: "go-fest2025", asset: "sb_GoFest2025", series: "gofest", scope: "global", en: "Go Fest2025", date: "", code: "LC_SPECIALBACKGROUND_2025_GLOBAL_GOFEST_REGI_006", vfx: true, pokemon: [] },
  { id: "go-fest2025-eternatus", asset: "sb_GoFest2025_Eternatus", series: "gofest", scope: "global", en: "Go Fest2025 Eternatus", date: "", code: "LC_SPECIALBACKGROUND_2025_GLOBAL_GOFEST_DD_001", vfx: true, pokemon: [] },
  { id: "go-fest2026-global", asset: "sb_GoFest2026_global", series: "gofest", scope: "global", en: "GO Fest 2026 Global", date: "July 12th - 13th 2026", code: "LC_SPECIALBACKGROUND_2026_GLOBAL_GOFEST_001", vfx: true, pokemon: [] },
  { id: "go-fest2026-mewtwo", asset: "sb_GoFest2026_mewtwo", series: "gofest", scope: "global", en: "GO Fest 2026 Mewtwo", date: "July 12th - 13th 2026", code: "LC_SPECIALBACKGROUND_2026_MEWTWO_002", vfx: true, pokemon: [] },
  { id: "go-tour2025-black", asset: "sb_GoTour2025_black", series: "gotour", scope: "global", en: "Go Tour2025 Black", date: "", code: "LC_SPECIALBACKGROUND_2026_10TH_ANNIVERSARY_001", vfx: true, pokemon: [] },
  { id: "go-tour2025-black-white", asset: "sb_GoTour2025_black_white", series: "gotour", scope: "global", en: "Go Tour2025 Black White", date: "", code: "", vfx: false, pokemon: [] },
  { id: "go-tour2025-enigma", asset: "sb_GoTour2025_enigma", series: "gotour", scope: "global", en: "GO Tour Enigma", date: "February 21st - 23rd 2025", code: "", vfx: false, pokemon: [] },
  { id: "go-tour2025-white", asset: "sb_GoTour2025_white", series: "gotour", scope: "global", en: "Go Tour2025 White", date: "", code: "", vfx: false, pokemon: [] },
  { id: "go-tour2026-diamond", asset: "sb_GoTour2026_diamond", series: "gotour", scope: "global", en: "GO Tour 2026 Diamond", date: "February 23rd - February 27th 2026", code: "LC_SPECIALBACKGROUND_2026_GLOBAL_DIAMOND_001", vfx: true, pokemon: [] },
  { id: "go-tour2026-gold", asset: "sb_GoTour2026_gold", series: "gotour", scope: "global", en: "GO Tour 2026 Gold", date: "February 23rd - February 27th 2026", code: "LC_SPECIALBACKGROUND_2026_GLOBAL_GOLD_001", vfx: true, pokemon: [] },
  { id: "go-tour2026-mega", asset: "sb_GoTour2026_mega", series: "gotour", scope: "global", en: "GO Tour 2026 Mega", date: "February 23rd - February 27th 2026", code: "LC_SPECIALBACKGROUND_2026_GLOBAL_MEGA_002", vfx: true, pokemon: [] },
  { id: "go-tour2026-pearl", asset: "sb_GoTour2026_pearl", series: "gotour", scope: "global", en: "GO Tour 2026 Pearl", date: "February 23rd - February 27th 2026", code: "LC_SPECIALBACKGROUND_2026_GLOBAL_PEARL_001", vfx: true, pokemon: [] },
  { id: "go-tour2026-ruby", asset: "sb_GoTour2026_ruby", series: "gotour", scope: "global", en: "GO Tour 2026 Ruby", date: "February 23rd - February 27th 2026", code: "LC_SPECIALBACKGROUND_2026_GLOBAL_RUBY_001", vfx: true, pokemon: [] },
  { id: "go-tour2026-sapphire", asset: "sb_GoTour2026_sapphire", series: "gotour", scope: "global", en: "GO Tour 2026 Sapphire", date: "February 23rd - February 27th 2026", code: "LC_SPECIALBACKGROUND_2026_GLOBAL_SAPPHIRE_001", vfx: true, pokemon: [] },
  { id: "go-tour2026-silver", asset: "sb_GoTour2026_silver", series: "gotour", scope: "global", en: "GO Tour 2026 Silver", date: "February 23rd - February 27th 2026", code: "LC_SPECIALBACKGROUND_2026_GLOBAL_SILVER_001", vfx: true, pokemon: [] },
  { id: "go-tour2026-x", asset: "sb_GoTour2026_x", series: "gotour", scope: "global", en: "GO Tour 2026 X", date: "February 23rd - February 27th 2026", code: "LC_SPECIALBACKGROUND_2026_GLOBAL_X_001", vfx: true, pokemon: [] },
  { id: "go-tour2026-y", asset: "sb_GoTour2026_y", series: "gotour", scope: "global", en: "GO Tour 2026 Y", date: "February 23rd - February 27th 2026", code: "LC_SPECIALBACKGROUND_2026_GLOBAL_Y_001", vfx: true, pokemon: [] },
  { id: "mid-autumn", asset: "sb_MidAutumn", series: "sbmisc", scope: "global", en: "Mid Autumn", date: "", code: "", vfx: false, pokemon: [] },
  { id: "observatory-exhibition-tour", asset: "sb_ObservatoryExhibitionTour", series: "sbmisc", scope: "global", en: "Observatory Exhibition Tour", date: "", code: "LC_SPECIALBACKGROUND_OBSERVATORY_EXHIBITION_TOUR", vfx: false, pokemon: [] },
  { id: "pattern-wild", asset: "sb_PatternWild", series: "sbmisc", scope: "global", en: "Pattern Wild", date: "", code: "", vfx: false, pokemon: [] },
  { id: "season17-duel-destiny", asset: "sb_Season17_DuelDestiny", series: "season", scope: "global", en: "Season17 Duel Destiny", date: "", code: "LC_SPECIALBACKGROUND_2025_SEASON17", vfx: false, pokemon: [] },
  { id: "season18-might-and-mastery", asset: "sb_Season18_MightAndMastery", series: "season", scope: "global", en: "Might and Mastery", date: "March 8th 2025 March 22nd 2025 April 27th 2025 May 11th 2025 May 24th 2025", code: "LC_SPECIALBACKGROUND_2025_S18", vfx: true, pokemon: [] },
  { id: "season19-delightful-days", asset: "sb_Season19_DelightfulDays", series: "season", scope: "global", en: "Delightful Days", date: "June - September 2025", code: "LC_SPECIALBACKGROUND_2025_SEASON19", vfx: true, pokemon: [] },
  { id: "season20-tales-of-transformation", asset: "sb_Season20_TalesOfTransformation", series: "season", scope: "global", en: "Tales of Transformation", date: "September 14th - December 2nd 2025", code: "LC_SPECIALBACKGROUND_2025_SEASON20", vfx: true, pokemon: [] },
  { id: "team-leader-blue", asset: "sb_TeamLeader_blue", series: "teamleader", scope: "global", en: "Team Leader Blue", date: "", code: "LC_SPECIALBACKGROUND_TEAM_BLUE", vfx: true, pokemon: [] },
  { id: "team-leader-red", asset: "sb_TeamLeader_red", series: "teamleader", scope: "global", en: "Team Leader Red", date: "", code: "LC_SPECIALBACKGROUND_TEAM_RED", vfx: true, pokemon: [] },
  { id: "team-leader-yellow", asset: "sb_TeamLeader_yellow", series: "teamleader", scope: "global", en: "Team Leader Yellow", date: "", code: "LC_SPECIALBACKGROUND_TEAM_YELLOW", vfx: true, pokemon: [] },
  { id: "world-special-blue", asset: "sb_WorldSpecial_Blue", series: "sbmisc", scope: "global", en: "World Special Blue", date: "", code: "LC_SPECIALBACKGROUND_2026_WCS", vfx: true, pokemon: [] },
  { id: "arraia-2026", asset: "sb_arraia_2026", series: "sbmisc", scope: "global", en: "Pokemon GO Arraia 2026", date: "June 23rd - June 30th 2026", code: "LC_SPECIALBACKGROUND_2026_ARRAIA", vfx: true, pokemon: [] },
  { id: "lego-2026", asset: "sb_lego_2026", series: "sbmisc", scope: "global", en: "LEGO Pokemon", date: "June 12th - 14th 2026", code: "LC_SPECIALBACKGROUND_LEGO_2026_01", vfx: false, pokemon: [] },
  { id: "s24-sep-2026", asset: "sb_s24_sep_2026", series: "sbmisc", scope: "global", en: "S24 Sep 2026", date: "", code: "", vfx: false, pokemon: [] },
];

export const BG_CARD_COUNT = 240;
